FROM maven:3.5-jdk-8-alpine as build
WORKDIR /app
COPY Spring_Security_backend_test_428 .
RUN mvn -B -f pom.xml dependency:go-offline
RUN mvn -B package -DskipTests

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/gateway-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar gateway-0.0.1-SNAPSHOT.jar"]